-- Final schema: staff_profiles
-- All IDs: INT AUTO_INCREMENT
-- Merged from: 034_create_staff_profiles.sql, 110_fix_database_schema_inconsistencies.sql
-- Changes: added contact/address columns, salary_type, renamed monthly_salary->salary_amount,
--          added pf_account_number, esic_account_number
CREATE TABLE staff_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id INT NOT NULL,
    branch_id INT NOT NULL,
    user_id INT NOT NULL,
    employee_id VARCHAR(50),
    contact_number VARCHAR(20),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    dob DATE,
    aadhaar_number VARCHAR(255),
    pan_number VARCHAR(255),
    profile_photo_url TEXT,
    employee_type VARCHAR(20) NOT NULL,
    designation VARCHAR(150),
    department VARCHAR(100),
    joining_date DATE,
    employment_type VARCHAR(20) NOT NULL DEFAULT 'full_time',
    employment_status VARCHAR(20) NOT NULL DEFAULT 'active',
    salary_type VARCHAR(20),
    salary_amount DECIMAL(12,2),
    bank_account_number VARCHAR(255),
    bank_ifsc VARCHAR(20),
    bank_name VARCHAR(100),
    pf_applicable TINYINT(1) NOT NULL DEFAULT 0,
    pf_account_number VARCHAR(100),
    esic_applicable TINYINT(1) NOT NULL DEFAULT 0,
    esic_account_number VARCHAR(100),
    tds_applicable TINYINT(1) NOT NULL DEFAULT 0,
    professional_tax_applicable TINYINT(1) NOT NULL DEFAULT 0,
    emergency_contact_name VARCHAR(100),
    emergency_contact_number VARCHAR(20),
    current_address TEXT,
    permanent_address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    max_lectures_per_day INTEGER,
    max_lectures_per_week INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    created_by INT,
    updated_by INT,
    UNIQUE(tenant_id, user_id),
    UNIQUE(tenant_id, employee_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
