-- Insert SaaS Admin permissions (auto-increment IDs)
INSERT IGNORE INTO permissions (module, action, code, description) VALUES
('tenant', 'view', 'tenant.view', 'List and view all tenant records'),
('tenant', 'create', 'tenant.create', 'Onboard new tenant'),
('tenant', 'update', 'tenant.update', 'Edit tenant profile/settings'),
('tenant', 'activate', 'tenant.activate', 'Activate a draft/suspended tenant'),
('tenant', 'suspend', 'tenant.suspend', 'Suspend a tenant access'),
('tenant', 'delete', 'tenant.delete', 'Soft-delete a tenant'),
('plan', 'view', 'plan.view', 'View subscription plans'),
('plan', 'create', 'plan.create', 'Create a new subscription plan'),
('plan', 'update', 'plan.update', 'Modify plan details/pricing'),
('plan', 'delete', 'plan.delete', 'Deactivate a plan'),
('subscription', 'view', 'subscription.view', 'View all tenant subscriptions'),
('subscription', 'assign', 'subscription.assign', 'Assign a plan to a tenant'),
('subscription', 'update', 'subscription.update', 'Change subscription status/dates'),
('subscription', 'cancel', 'subscription.cancel', 'Cancel a tenant subscription'),
('module', 'view', 'module.view', 'View module registry'),
('module', 'update', 'module.update', 'Change module lifecycle state'),
('feature_flag', 'view', 'feature_flag.view', 'View feature flags'),
('feature_flag', 'toggle', 'feature_flag.toggle', 'Enable/disable feature flags globally'),
('approval', 'view', 'approval.view', 'View approval requests'),
('approval', 'process', 'approval.process', 'Approve or reject requests'),
('support', 'view', 'support.view', 'View all support tickets'),
('support', 'reply', 'support.reply', 'Reply to a support ticket'),
('support', 'resolve', 'support.resolve', 'Mark a ticket as resolved'),
('communication', 'send', 'communication.send', 'Broadcast communications to tenants'),
('billing', 'view', 'billing.view', 'View invoices and billing data'),
('billing', 'export', 'billing.export', 'Export billing data as CSV'),
('analytics', 'view', 'analytics.view', 'View product analytics'),
('report', 'view', 'report.view', 'View SaaS reports'),
('audit_log', 'view', 'audit_log.view', 'View audit trail'),
('system_config', 'view', 'system_config.view', 'View system configuration'),
('system_config', 'update', 'system_config.update', 'Modify system configuration'),
('role', 'view', 'role.view', 'View roles and permissions matrix'),
('role', 'update', 'role.update', 'Modify role permissions'),
('user', 'view', 'user.view', 'View platform users'),
('user', 'update', 'user.update', 'Update user status/access');
