CREATE TABLE staff_profiles (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id INT NOT NULL REFERENCES tenants(id),
    branch_id VARCHAR(36) NOT NULL REFERENCES branches(id),
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    employee_id VARCHAR(50),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    dob DATE,
    aadhaar_number VARCHAR(255),
    pan_number VARCHAR(255),
    profile_photo_url TEXT,
    employee_type VARCHAR(20) NOT NULL,
    designation VARCHAR(150),
    department VARCHAR(100),
    joining_date DATE,
    employment_type VARCHAR(20) NOT NULL DEFAULT 'full_time',
    employment_status VARCHAR(20) NOT NULL DEFAULT 'active',
    monthly_salary DECIMAL(12,2),
    bank_account_number VARCHAR(255),
    bank_ifsc VARCHAR(20),
    bank_name VARCHAR(100),
    pf_applicable TINYINT(1) NOT NULL DEFAULT 0,
    esic_applicable TINYINT(1) NOT NULL DEFAULT 0,
    tds_applicable TINYINT(1) NOT NULL DEFAULT 0,
    professional_tax_applicable TINYINT(1) NOT NULL DEFAULT 0,
    max_lectures_per_day INTEGER,
    max_lectures_per_week INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    created_by INT,
    updated_by INT,
    UNIQUE(tenant_id, user_id),
    UNIQUE(tenant_id, employee_id)
);
